# Generated by Django 4.1.5 on 2023-01-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PixelArt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
