# Generated by Django 4.1.5 on 2023-01-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixelart',
            name='category',
            field=models.CharField(choices=[('PERSONAGEM', 'Personagem'), ('ORIGINAL', 'Original')], default='', max_length=100),
        ),
    ]
