# Generated by Django 4.1.5 on 2023-01-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_pixelart_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixelart',
            name='path',
            field=models.ImageField(blank=True, upload_to='pixelArts/'),
        ),
    ]
